# Generated by Django 5.1.5 on 2025-02-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_options_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('reservation_date', 'reservation_time')},
        ),
    ]
